# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BEMSauth', '0001_initial'),
        ('BEMSinstances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEMSeducationInstance',
            fields=[
                ('bemsinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSinstances.BEMSInstance')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
            bases=('BEMSinstances.bemsinstance',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('bemsprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSauth.BEMSProfile')),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
            },
            bases=('BEMSauth.bemsprofile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('bemsprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSauth.BEMSProfile')),
                ('responsible', models.ManyToManyField(to='main.Parent')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
            bases=('BEMSauth.bemsprofile',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('bemsprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSauth.BEMSProfile')),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
            },
            bases=('BEMSauth.bemsprofile',),
        ),
    ]
