# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161003_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bemseducationinstance',
            options={'verbose_name': 'Inst\xe0ncia BEMS.education', 'verbose_name_plural': 'Inst\xe0ncies BEMS.education'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Perfil de Pare/Mare', 'verbose_name_plural': 'Perfil de Pares/Mares'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': "Perfil d'Estudiant", 'verbose_name_plural': "Perfils d'Estudiant"},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Perfil de Professor', 'verbose_name_plural': 'Perfils de Professor'},
        ),
    ]
