# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, b'Dilluns'), (2, b'Dimarts'), (3, b'Dimecres'), (4, b'Dijous'), (5, b'Divendres'), (6, b'Dissabte'), (7, b'Diumenge')], default=1)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Dia de Classe',
                'verbose_name_plural': 'Dies de Classe',
            },
        ),
        migrations.CreateModel(
            name='ClassUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('days', models.ManyToManyField(to='schedule.ClassDay')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Unitat de Classe',
                'verbose_name_plural': 'Unitats de Classe',
            },
        ),
        migrations.CreateModel(
            name='NonLectivePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Per\xedode no Lectiu',
                'verbose_name_plural': 'Per\xedodes no Lectius',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=6)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Curs Escolar',
                'verbose_name_plural': 'Cursos Escolars',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=6)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Assignatura',
                'verbose_name_plural': 'Assignatures',
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Subject Category',
                'verbose_name_plural': 'Subject Categories',
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Registre d'Horari",
                'verbose_name_plural': "Registre d'Horari",
            },
        ),
        migrations.CreateModel(
            name='WeeklyTimetableEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Classroom')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassDay')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Teacher')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassUnit')),
            ],
            options={
                'verbose_name': "Registre d'Horari Setmanal",
                'verbose_name_plural': "Registres d'Horari Setmanal",
            },
        ),
        migrations.CreateModel(
            name='ClassTrip',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='education.Student')),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
        migrations.CreateModel(
            name='NonLectiveDay',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('day', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
        migrations.CreateModel(
            name='NonLectiveHours',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='weekly_timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.WeeklyTimetableEntry'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.SubjectCategory'),
        ),
        migrations.AddField(
            model_name='subject',
            name='default_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Group'),
        ),
        migrations.AddField(
            model_name='subject',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='subject',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Stage'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='semesters',
            field=models.ManyToManyField(to='schedule.Semester'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='grades',
            field=models.ManyToManyField(to='institution.Grade'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='groups',
            field=models.ManyToManyField(to='institution.Group'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_schedule.nonlectiveperiod_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='stages',
            field=models.ManyToManyField(to='institution.Stage'),
        ),
    ]
