# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161003_2212'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('institution', '0002_auto_20160908_1344'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLectivePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Non Lective Period',
                'verbose_name_plural': 'Non Lective Periods',
            },
        ),
        migrations.RenameField(
            model_name='weeklytimetableentry',
            old_name='date',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='weeklytimetableentry',
            old_name='time',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ClassTrip',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='main.Student')),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
        migrations.CreateModel(
            name='NonLectiveDay',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('day', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
        migrations.CreateModel(
            name='NonLectiveHours',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='grades',
            field=models.ManyToManyField(to='institution.Grade'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='groups',
            field=models.ManyToManyField(to='institution.Group'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_schedule.nonlectiveperiod_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='nonlectiveperiod',
            name='stages',
            field=models.ManyToManyField(to='institution.Stage'),
        ),
    ]
