# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161003_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classday',
            options={'verbose_name': 'Dia de Classe', 'verbose_name_plural': 'Dies de Classe'},
        ),
        migrations.AlterModelOptions(
            name='classunit',
            options={'verbose_name': 'Unitat de Classe', 'verbose_name_plural': 'Unitats de Classe'},
        ),
        migrations.AlterModelOptions(
            name='majorsubject',
            options={'verbose_name': 'Assignatura de Modalitat', 'verbose_name_plural': 'Assignatures de Modalitat'},
        ),
        migrations.AlterModelOptions(
            name='nonlectiveperiod',
            options={'verbose_name': 'Per\xedode no Lectiu', 'verbose_name_plural': 'Per\xedodes no Lectius'},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': 'Curs Escolar', 'verbose_name_plural': 'Cursos Escolars'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestres'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Assignatura', 'verbose_name_plural': 'Assignatures'},
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'verbose_name': "Registre d'Horari", 'verbose_name_plural': "Registre d'Horari"},
        ),
        migrations.AlterModelOptions(
            name='weeklytimetableentry',
            options={'verbose_name': "Registre d'Horari Setmanal", 'verbose_name_plural': "Registres d'Horari Setmanal"},
        ),
        migrations.AlterField(
            model_name='classday',
            name='day',
            field=models.IntegerField(choices=[(1, b'Dilluns'), (2, b'Dimarts'), (3, b'Dimecres'), (4, b'Dijous'), (5, b'Divendres'), (6, b'Dissabte'), (7, b'Diumenge')], default=1),
        ),
    ]
