# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161027_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLectiveDates',
            fields=[
                ('nonlectiveperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.NonLectivePeriod')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('schedule.nonlectiveperiod',),
        ),
    ]
