# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_nonlectivedates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classday',
            options={'verbose_name': 'Class Day', 'verbose_name_plural': 'Class Days'},
        ),
        migrations.AlterModelOptions(
            name='classunit',
            options={'verbose_name': 'Class Unit', 'verbose_name_plural': 'Class Units'},
        ),
        migrations.AlterModelOptions(
            name='nonlectiveperiod',
            options={'verbose_name': 'Non Lective Period', 'verbose_name_plural': 'Non Lective Periods'},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': 'School Year', 'verbose_name_plural': 'School Years'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'verbose_name': 'Timetable Entry', 'verbose_name_plural': 'Timetable Entry'},
        ),
        migrations.AlterModelOptions(
            name='weeklytimetableentry',
            options={'verbose_name': 'Weekly Timetable Entry', 'verbose_name_plural': 'Weekly Timetable Entries'},
        ),
    ]
