# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BEMSinstances', '0001_initial'),
        ('BEMSauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEMSeducationInstance',
            fields=[
                ('bemsinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSinstances.BEMSInstance')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Inst\xe0ncia BEMS.education',
                'verbose_name_plural': 'Inst\xe0ncies BEMS.education',
            },
            bases=('BEMSinstances.bemsinstance',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('bemsprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSauth.BEMSProfile')),
            ],
            options={
                'verbose_name': 'Perfil de Pare/Mare',
                'verbose_name_plural': 'Perfil de Pares/Mares',
            },
            bases=('BEMSauth.bemsprofile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('bemsprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSauth.BEMSProfile')),
                ('responsible', models.ManyToManyField(to='education.Parent')),
            ],
            options={
                'verbose_name': "Perfil d'Estudiant",
                'verbose_name_plural': "Perfils d'Estudiant",
            },
            bases=('BEMSauth.bemsprofile',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('bemsprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BEMSauth.BEMSProfile')),
            ],
            options={
                'verbose_name': 'Perfil de Professor',
                'verbose_name_plural': 'Perfils de Professor',
            },
            bases=('BEMSauth.bemsprofile',),
        ),
    ]
