# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20161027_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bemseducationinstance',
            options={'verbose_name': 'BEMS.education Instance', 'verbose_name_plural': 'BEMS.education Instances'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent Profile', 'verbose_name_plural': 'Parent Profiles'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
    ]
