# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
            },
        ),
        migrations.CreateModel(
            name='YearEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
            },
        ),
        migrations.CreateModel(
            name='ClassEnroll',
            fields=[
                ('enroll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.Enroll')),
            ],
            options={
                'verbose_name': 'Subject Enrollment',
                'verbose_name_plural': 'Subject Enrollments',
            },
            bases=('enrollment.enroll',),
        ),
        migrations.CreateModel(
            name='MajorEnroll',
            fields=[
                ('enroll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enrollment.Enroll')),
            ],
            options={
                'verbose_name': 'Major Subject Enrollment',
                'verbose_name_plural': 'Major Subject Enrollments',
            },
            bases=('enrollment.enroll',),
        ),
    ]
