# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': "Matr\xedcula d'Assignatura",
                'verbose_name_plural': "Matr\xedcules d'Assignatura",
            },
        ),
        migrations.CreateModel(
            name='YearEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Group')),
            ],
            options={
                'verbose_name': "Matr\xedcula de l'Alumnat",
                'verbose_name_plural': "Matr\xedcules de l'Alumnat",
            },
        ),
    ]
