# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('education', '0001_initial'),
        ('institution', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearenroll',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.SchoolYear'),
        ),
        migrations.AddField(
            model_name='yearenroll',
            name='semester',
            field=models.ManyToManyField(to='schedule.Semester'),
        ),
        migrations.AddField(
            model_name='yearenroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Student'),
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='semester',
            field=models.ManyToManyField(to='schedule.Semester'),
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Student'),
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject'),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institution.Group'),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.Student'),
        ),
    ]
