# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearenroll',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Group'),
        ),
    ]
