# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20161027_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Group'),
        ),
    ]
