# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('schedule', '0001_initial'),
        ('enrollment', '0002_yearenroll_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearenroll',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.SchoolYear'),
        ),
        migrations.AddField(
            model_name='yearenroll',
            name='semester',
            field=models.ManyToManyField(to='schedule.Semester'),
        ),
        migrations.AddField(
            model_name='yearenroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='semester',
            field=models.ManyToManyField(to='schedule.Semester'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='majorenroll',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MajorSubject'),
        ),
        migrations.AddField(
            model_name='classenroll',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject'),
        ),
    ]
