# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20160908_1344'),
        ('main', '0002_auto_20161003_2212'),
        ('enrollment', '0003_auto_20160908_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institution.Group')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
    ]
