# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_studentstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classenroll',
            options={'verbose_name': "Matr\xedcula d'Assignatura", 'verbose_name_plural': "Matr\xedcules d'Assignatura"},
        ),
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': 'Matr\xedcula de Classe', 'verbose_name_plural': 'Matr\xedcules de Classe'},
        ),
        migrations.AlterModelOptions(
            name='majorenroll',
            options={'verbose_name': "Matr\xedcula d'Assignatura de Modalitat", 'verbose_name_plural': "Matr\xedcules d'Assignatura de Modalitat"},
        ),
        migrations.AlterModelOptions(
            name='yearenroll',
            options={'verbose_name': "Matr\xedcula de l'Alumnat", 'verbose_name_plural': "Matr\xedcules de l'Alumnat"},
        ),
    ]
