# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('floor', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aules',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=6)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
            ],
            options={
                'verbose_name': 'Curs',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Classroom')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Grade')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
            ],
            options={
                'verbose_name': 'Grup',
                'verbose_name_plural': 'Grups',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=6)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.BEMSeducationInstance')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='grade',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Stage'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
    ]
