# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20160908_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aules'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Curs', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grup', 'verbose_name_plural': 'Grups'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
    ]
