# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BEMSauth', '0003_userrequest'),
        ('schedule', '0004_auto_20161111_1528'),
        ('education', '0005_auto_20161111_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PunishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='punishment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.PunishmentType'),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.IncidentCategory'),
        ),
        migrations.AddField(
            model_name='incident',
            name='classUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TimetableEntry'),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_created_by', to='BEMSauth.BEMSProfile'),
        ),
        migrations.AddField(
            model_name='incident',
            name='punishment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.Punishment'),
        ),
        migrations.AddField(
            model_name='incident',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Student'),
        ),
        migrations.AddField(
            model_name='incident',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Teacher'),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.IncidentType'),
        ),
    ]
