# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('schedule', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetype',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BEMSeducationInstance'),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TimetableEntry'),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceType'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancetype',
            unique_together=set([('instance', 'char')]),
        ),
    ]
