# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_attendanceentry_student'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.TimetableEntry'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentry',
            unique_together=set([('student', 'timetable_entry')]),
        ),
    ]
