# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20160908_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceentry',
            options={'verbose_name': 'Attendance Entry', 'verbose_name_plural': 'Attendance Entries'},
        ),
        migrations.AlterModelOptions(
            name='attendancetype',
            options={'verbose_name': 'Attendance Type', 'verbose_name_plural': 'Attendance Types'},
        ),
    ]
