# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161007_1008'),
        ('schedule', '0003_auto_20161007_1008'),
        ('attendance', '0003_auto_20161003_2212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancetype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='attendancetype',
            name='instance',
        ),
        migrations.AlterModelOptions(
            name='attendanceentry',
            options={'verbose_name': "Registre d'Assist\xe8ncia", 'verbose_name_plural': "Registres d'Assist\xe8ncia"},
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='type',
            field=models.CharField(choices=[(b'F', b'Falta'), (b'R', b'Retard'), (b'J', b'Justified'), (b'C', b'Consergeria')], default='F', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentry',
            unique_together=set([('student', 'timetable_entry')]),
        ),
        migrations.DeleteModel(
            name='AttendanceType',
        ),
    ]
